# Generated by Django 2.0 on 2019-11-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FansUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户名')),
                ('nickname', models.CharField(blank=True, max_length=128, null=True, verbose_name='昵称')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='邮箱')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='密码')),
                ('wb_id', models.CharField(blank=True, max_length=64, null=True)),
                ('head', models.CharField(blank=True, max_length=128, null=True)),
                ('sex', models.CharField(blank=True, max_length=16, null=True)),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('register_ip', models.CharField(blank=True, max_length=32, null=True)),
                ('last_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fans_user',
            },
        ),
    ]
