# Generated by Django 2.0 on 2019-11-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fansuser',
            name='head',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
