# Generated by Django 2.0.12 on 2019-11-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191119_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='fansuser',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='用户简介'),
        ),
        migrations.AddField(
            model_name='fansuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
