# Generated by Django 2.0.12 on 2019-11-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191120_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='fansuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='用户是否激活'),
        ),
        migrations.AddField(
            model_name='fansuser',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='用户是否被禁用'),
        ),
    ]
