# Generated by Django 2.0.12 on 2019-12-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(blank=True, max_length=124, null=True)),
                ('b_user', models.IntegerField(null=True)),
                ('b_content', models.CharField(blank=True, max_length=400, null=True)),
                ('b_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
