# Generated by Django 2.0.12 on 2019-11-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserOfFans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=232, verbose_name='密码')),
                ('email', models.CharField(blank=True, max_length=232, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('sex', models.CharField(blank=True, max_length=16, null=True, verbose_name='性别')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('register_ip', models.CharField(blank=True, max_length=32, null=True, verbose_name='注册IP')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='上次修改时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='用户简介')),
                ('is_active', models.BooleanField(default=False, verbose_name='用户是否激活')),
                ('is_delete', models.BooleanField(default=False, verbose_name='用户是否被禁用')),
            ],
            options={
                'db_table': 'user_of_fans',
            },
        ),
    ]
